(function () {
  'use strict';
  const M=window.SymmetryMath,P=window.SymmetryPointGroups,A=window.SymmetryAdvanced,C=window.SymmetryCourse,L=window.SymmetryLearning;
  if(!M||!P||!A||!C||!document.getElementById('property-root'))return;
  const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const hm=s=>esc(s).replace(/-(\d)/g,'<span class="overbar">$1</span>');
  const fmt=x=>(Math.abs(x)<.0005?0:x).toFixed(2),xyz=p=>'('+p.map(fmt).join(', ')+')';
  const groups=L.pointGroups.map(g=>'<option value="'+esc(g.hm)+'">'+esc(g.hm.replace(/-(\d)/g,'$1\u0305'))+' / '+esc(g.schoenflies)+'</option>').join('');
  const section=(title,lead,body,pages)=>'<section class="course-section panel"><p class="eyebrow">LECTURE 04 · LEARN BY DOING</p><h2>'+title+'</h2><span class="course-ref">L04 · PDF 第 '+pages+' 页</span><p class="lead">'+lead+'</p>'+body+'</section>';
  const surface=(id,title,extra='')=>'<div class="course-surface '+extra+'"><span class="mini-label">'+title+'</span><canvas id="'+id+'" tabindex="0" aria-label="'+title+'。拖动视角，滚轮缩放，方向键调整视角。"></canvas><small>拖动观察 · 滚轮缩放 · 坐标为教学约定</small></div>';
  function open(spec){location.hash=spec.page;if(spec.page==='crystal')document.dispatchEvent(new CustomEvent('symmetry-crystal-open',{detail:spec}));if(spec.hm)document.dispatchEvent(new CustomEvent('symmetry-atlas-select',{detail:{hm:spec.hm}}));requestAnimationFrame(()=>{if(spec.target)$(spec.target)?.scrollIntoView({block:'start',behavior:'auto'});else window.scrollTo({top:0,behavior:'auto'});});}
  document.addEventListener('click',e=>{const link=e.target.closest('[data-course-link]'),jump=e.target.closest('[data-course-scroll]');if(link)open({page:link.dataset.courseLink});if(jump)$(jump.dataset.courseScroll)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});
  document.addEventListener('symmetry-course-explore',e=>open(e.detail));
  const sceneList=[];
  class Scene{
    constructor(id,data){this.canvas=$(id);this.ctx=this.canvas.getContext('2d');this.data=data;this.camera={yaw:-.48,pitch:.43,zoom:1};let drag=null;
      this.canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId);});
      this.canvas.addEventListener('pointermove',e=>{if(!drag)return;this.camera.yaw+=(e.clientX-drag.x)*.008;this.camera.pitch=M.clamp(this.camera.pitch+(e.clientY-drag.y)*.008,-1.5,1.5);drag={x:e.clientX,y:e.clientY};this.draw();});
      ['pointerup','pointercancel'].forEach(t=>this.canvas.addEventListener(t,()=>{drag=null;}));
      this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.camera.zoom=M.clamp(this.camera.zoom*Math.exp(-e.deltaY*.0015),.5,2);this.draw();},{passive:false});
      this.canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')this.camera.yaw-=.1;if(e.key==='ArrowRight')this.camera.yaw+=.1;if(e.key==='ArrowUp')this.camera.pitch=M.clamp(this.camera.pitch+.1,-1.5,1.5);if(e.key==='ArrowDown')this.camera.pitch=M.clamp(this.camera.pitch-.1,-1.5,1.5);if(e.key==='+'||e.key==='=')this.camera.zoom=M.clamp(this.camera.zoom*1.1,.5,2);if(e.key==='-')this.camera.zoom=M.clamp(this.camera.zoom/1.1,.5,2);this.draw();});sceneList.push(this);
    }
    draw(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h||!this.ctx)return;const ratio=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==Math.round(w*ratio)||this.canvas.height!==Math.round(h*ratio)){this.canvas.width=Math.round(w*ratio);this.canvas.height=Math.round(h*ratio);}const ctx=this.ctx;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);const data=this.data(),cam=this.camera,center=data.center||[0,0,0],scale=Math.min(w,h)*.32/(data.radius||1.5)*cam.zoom;
      const project=p=>{const q=M.subtract(p,center),x=Math.cos(cam.yaw)*q[0]-Math.sin(cam.yaw)*q[1],y=Math.sin(cam.yaw)*q[0]+Math.cos(cam.yaw)*q[1];return{x:w/2+x*scale,y:h*.54-(Math.cos(cam.pitch)*q[2]+Math.sin(cam.pitch)*y)*scale,depth:-Math.cos(cam.pitch)*y+Math.sin(cam.pitch)*q[2]};};
      const line=(points,color,dash=[])=>{if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>{const q=project(p);if(!i)ctx.moveTo(q.x,q.y);else ctx.lineTo(q.x,q.y);});ctx.strokeStyle=color;ctx.lineWidth=1.2;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);};
      (data.lines||[]).forEach(l=>line(l.points,l.color||'#087e8277',l.dash||[]));
      (data.points||[]).map(p=>({...p,q:project(p.position)})).sort((a,b)=>a.q.depth-b.q.depth).forEach(p=>{ctx.beginPath();ctx.arc(p.q.x,p.q.y,p.radius?Math.max(3,p.radius*scale):5,0,2*Math.PI);ctx.fillStyle=p.hollow?'#ffffffc9':p.color||'#087e82';ctx.fill();ctx.strokeStyle=p.color||'#087e82';ctx.lineWidth=1.5;ctx.stroke();if(p.label){ctx.fillStyle='#17384b';ctx.font='10px system-ui';ctx.fillText(p.label,p.q.x+8,p.q.y-8);}});
    }
  }
  function render(){sceneList.forEach(s=>s.draw());}
  function axes(radius){return[[1,0,0],[0,1,0],[0,0,1]].map((v,i)=>({points:[M.scale(v,-radius),M.scale(v,radius)],color:['#7290ad88','#7c9f8288','#b3916c88'][i],dash:[4,5]}));}

  $('subgroup-root').innerHTML=section('少一些操作，仍然是一个群','不能随便删掉操作：保留下来的集合仍要包含 E，并满足闭包与逆元。',
    '<div class="course-controls"><label for="course-subgroup">选择一组嵌入关系 <select id="course-subgroup"><option value="0">4/mmm → 4mm</option><option value="1">4/mmm → 2/m</option><option value="2">6/mmm → 6mm</option><option value="3">m3̄m → 4̄3m</option><option value="4">3̄m → 32</option></select></label><button type="button" class="secondary-button" id="course-child-atlas">看子群的三维模型 →</button></div><div class="course-subgroup-counts" id="course-subgroup-counts"></div><p id="course-subgroup-note"></p><div class="course-op-list" id="course-subgroup-ops"></div><div class="course-notice"><p>绿色：子群保留的操作；浅棕：从母群去掉的操作。这里比较的是已经嵌入同一坐标系的具体实例；同一种子群还可能有不同方向的嵌入。</p></div><details><summary>为什么“群阶整除”还不足以证明子群？</summary><p>有限群的子群阶数一定整除母群阶数，但反过来不成立。必须核对其操作确实属于母群，并在组合和取逆下封闭。群本身也属于自己的子群；这里显示的都是严格少一些操作的真子群。</p></details>','18–19');
  const subgroupPairs=[['4/mmm','4mm'],['4/mmm','2/m'],['6/mmm','6mm'],['m-3m','-43m'],['-3m','32']];
  function updateSubgroup(){const [parent,child]=subgroupPairs[Number($('course-subgroup').value)],g=P.getGroup(parent),h=P.getGroup(child),result=A.subgroup(parent,child);if(!result.isSubgroup)throw new Error('Teaching subgroup orientation mismatch: '+child);const retained=g.operations.map(op=>h.operations.some(x=>M.matrixError(op.matrix,x.matrix)<1e-7));$('course-subgroup-counts').innerHTML='<span><b>'+g.operations.length+'</b>母群操作</span><span><b>'+h.operations.length+'</b>子群操作</span><span><b>'+g.operations.length/h.operations.length+'</b>指数 [G:H]</span>';$('course-subgroup-note').innerHTML=hm(parent)+' ⊃ '+hm(child)+' · E、逆元和组合闭包全部保留。'+(child==='2/m'?'本例二重轴沿 y，垂直镜面是 xz 面。':'');$('course-subgroup-ops').innerHTML=g.operations.map((op,i)=>'<span class="'+(retained[i]?'kept':'removed')+'">'+esc(op.label)+'</span>').join('');}
  $('course-subgroup').addEventListener('change',updateSubgroup);$('course-child-atlas').addEventListener('click',()=>open({page:'atlas',hm:subgroupPairs[Number($('course-subgroup').value)][1],target:'point-group-viewer'}));updateSubgroup();

  $('property-root').innerHTML=section('结构的对称性，约束物性的方向','Neumann 原理：物性必须保留晶体点群的全部对称性；物性也可以拥有更多对称性。',
    '<div class="course-controls"><label for="course-property-group">点群 <select id="course-property-group">'+groups+'</select></label><button class="secondary-button" type="button" id="course-quartz">石英 · 32</button><button class="secondary-button" type="button" id="course-corundum">刚玉 · 3̄m</button><button class="quiet-button" type="button" id="course-property-camera">↺ 视角</button></div><div class="course-chips" id="course-property-chips"></div><div class="course-property-grid"><div><div class="course-two">'+surface('course-tensor-before','① 任意假设的二阶张量')+surface('course-tensor-after','② 保留所选点群后的张量')+'</div><div class="course-sliders"><label>Txx <input type="range" id="course-txx" min="1" max="5" step=".1" value="1.4"><output id="course-txx-value"></output></label><label>Tyy <input type="range" id="course-tyy" min="1" max="5" step=".1" value="2.7"><output id="course-tyy-value"></output></label><label>Tzz <input type="range" id="course-tzz" min="1" max="5" step=".1" value="4.3"><output id="course-tzz-value"></output></label></div><p>对每个操作 R 求平均：T̄ = (1/|G|) Σ R T Rᵀ。右边仍是一个示例数值张量；其自由系数数目由点群决定。椭球用 xᵀT̄⁻¹x = 1 表达方向差异，单位任意，不是实测介电数据。</p></div><div class="course-property-results"><div class="course-result"><h3 id="course-tensor-title"></h3><div class="matrix compact" id="course-tensor-matrix"></div><p id="course-tensor-note"></p></div><div class="course-result"><h3>极性向量能留下什么？</h3><code id="course-vector-result"></code><p id="course-vector-note"></p><div class="course-sliders"><label>Px<input id="course-px" type="range" min="-1" max="1" step=".1" value=".6"></label><label>Py<input id="course-py" type="range" min="-1" max="1" step=".1" value=".4"></label><label>Pz<input id="course-pz" type="range" min="-1" max="1" step=".1" value=".8"></label></div><p>群平均投影给出所有操作都不改变的向量。某次输入平均为零，不代表这一点群必定非极性；判断看允许向量空间的维数。</p></div></div></div><div class="course-notice"><p id="course-piezo-note"></p></div><details><summary>石英与刚玉：相同的二阶形式，不同的奇数阶约束</summary><p>石英属于 32，刚玉属于 3̄m；这里是点群方向示意，不是这两种材料的原子模型。两群都使对称二阶极性张量成为 diag(a,a,c)，有 2 个独立系数。刚玉含反演，普通三阶极性压电张量变为其相反数，故线性体压电必须为零；石英允许非零压电。这个奇数阶论证不适用于自旋等轴矢量。</p><p>极性、手性、非中心对称是三个不同问题。极性允许自发极化的方向；是否实际存在极化、是否可用电场翻转而成为铁电体，还需材料证据。立方群的对称二阶张量是各向同性，但不能据此把所有高阶物性都称为各向同性。</p><p><a href="https://dictionary.iucr.org/Neumann%27s_principle" target="_blank" rel="noopener noreferrer">IUCr · Neumann 原理 ↗</a> · <a href="https://www.iucr.org/what-we-do/education/pamphlets/introduction-crystal-physics" target="_blank" rel="noopener noreferrer">晶体物性与张量 ↗</a></p></details>','17、21–22、29');
  const prop={hm:'32',tensor:null,averaged:null,polar:null};
  function freedom(hmValue){let total=0;[[0,0],[1,1],[2,2],[1,2],[0,2],[0,1]].forEach(([i,j])=>{const t=[[0,0,0],[0,0,0],[0,0,0]];t[i][j]=1;t[j][i]=1;total+=A.invariantTensor(hmValue,t)[i][j];});return Math.round(total);}
  function cholesky(t){const a=Math.sqrt(t[0][0]),b=t[1][0]/a,c=t[2][0]/a,d=Math.sqrt(t[1][1]-b*b),e=(t[2][1]-b*c)/d,f=Math.sqrt(t[2][2]-c*c-e*e);return[[a,0,0],[b,d,0],[c,e,f]];}
  function ellipsoid(t,color){const matrix=cholesky(t),lines=axes(2.6);for(let k=1;k<8;k++){const theta=Math.PI*k/8;lines.push({color,points:Array.from({length:73},(_,j)=>{const phi=j*2*Math.PI/72;return M.applyMatrix(matrix,[Math.sin(theta)*Math.cos(phi),Math.sin(theta)*Math.sin(phi),Math.cos(theta)]);})});}for(let k=0;k<12;k++){const phi=k*2*Math.PI/12;lines.push({color,points:Array.from({length:49},(_,j)=>{const theta=j*Math.PI/48;return M.applyMatrix(matrix,[Math.sin(theta)*Math.cos(phi),Math.sin(theta)*Math.sin(phi),Math.cos(theta)]);})});}return{radius:2.6,lines};}
  const beforeScene=new Scene('course-tensor-before',()=>ellipsoid(prop.tensor,'#99aab477')),afterScene=new Scene('course-tensor-after',()=>ellipsoid(prop.averaged,'#087e8288'));
  function updateProperty(){const info=L.pointGroups.find(g=>g.hm===prop.hm);prop.tensor=[[Number($('course-txx').value),.22,.12],[.22,Number($('course-tyy').value),.18],[.12,.18,Number($('course-tzz').value)]];prop.averaged=A.invariantTensor(prop.hm,prop.tensor);prop.polar=A.polarProjector(prop.hm);const polarDimension=Math.round(prop.polar.reduce((s,row,i)=>s+row[i],0)),dim=freedom(prop.hm),input=[$('course-px'),$('course-py'),$('course-pz')].map(el=>Number(el.value)),out=M.applyMatrix(prop.polar,input);['txx','tyy','tzz'].forEach(id=>$('course-'+id+'-value').textContent=Number($('course-'+id).value).toFixed(1));$('course-property-group').value=prop.hm;
    $('course-property-chips').innerHTML=[[info.centrosymmetric,'有反演中心','无反演中心'],[info.chiral,'仅正旋转 · 手性相容','含不正操作 · 非手性'],[polarDimension>0,'极性相容','非极性']].map(([on,yes,no])=>'<span class="course-chip '+(on?'':'off')+'">'+(on?yes:no)+'</span>').join('');
    $('course-tensor-title').innerHTML=hm(prop.hm)+' · '+dim+' 个独立二阶系数';$('course-tensor-matrix').innerHTML=prop.averaged.flat().map(x=>'<span>'+fmt(x)+'</span>').join('');$('course-tensor-note').textContent=dim===1?'三个主方向系数必须相同，对称二阶性质各向同性。':dim===2?'沿主轴与横向可以不同；两个横向系数相同。':'约束保留 '+dim+' 个独立系数。显示的是当前直角坐标系中的数值。';$('course-vector-result').textContent=xyz(input)+' → '+xyz(out);$('course-vector-note').textContent='允许向量空间维数：'+polarDimension+'。'+(polarDimension===0?'只有零向量能保持全部操作。':polarDimension===1?'允许沿一条固定方向；该方向由模型坐标约定。':polarDimension===2?'允许镜面内的任意向量。':'任意方向都允许。');$('course-piezo-note').textContent=info.centrosymmetric?'普通线性体压电：对称性禁止。反演把普通奇数阶极性张量变号；保持反演就只能为零。':prop.hm==='432'?'普通线性体压电：对称性禁止。432 虽然没有反演，全部旋转共同约束仍使压电张量为零。':'普通线性体压电：对称性允许。允许不等于预测实际强度或保证测得非零；极性也不等于铁电。';render();}
  function selectProperty(hmValue,sync=false){if(!P.getGroup(hmValue))return;prop.hm=hmValue;updateProperty();if(sync)document.dispatchEvent(new CustomEvent('symmetry-atlas-select',{detail:{hm:hmValue}}));}
  $('course-property-group').addEventListener('change',()=>selectProperty($('course-property-group').value,true));$('course-quartz').addEventListener('click',()=>selectProperty('32',true));$('course-corundum').addEventListener('click',()=>selectProperty('-3m',true));['txx','tyy','tzz','px','py','pz'].forEach(id=>$('course-'+id).addEventListener('input',updateProperty));$('course-property-camera').addEventListener('click',()=>{[beforeScene,afterScene].forEach(s=>Object.assign(s.camera,{yaw:-.48,pitch:.43,zoom:1}));render();});document.addEventListener('symmetry-atlas-select',e=>selectProperty(e.detail.hm));selectProperty('32');

  $('color-root').innerHTML=section('转半圈，还要翻转颜色？','内部标签也属于对象的描述。先看普通二重旋转，再看“旋转＋二色翻转”。',
    '<div class="course-controls course-color-control"><button type="button" class="secondary-button" id="course-color-plain" aria-pressed="true">2 · 只转 180°</button><button type="button" class="secondary-button" id="course-color-prime" aria-pressed="false">2′ · 旋转＋换色</button><button type="button" class="secondary-button" id="course-color-swap" aria-pressed="false">1′ · 只换色</button></div><div class="course-two">'+surface('course-color-before','原始双色对象')+surface('course-color-after','操作完成后的双色对象')+'</div><div class="course-notice"><p id="course-color-result"></p></div><p>这两个点的位置在旋转后互换；若各点保留自己的黑白标签，对象不能重合。再做黑白翻转，位置与标签一起重合。“只换色”也不是这个对象的对称。</p><details><summary>二色翻转与原子种类互换的区别</summary><p>这里的黑白代表可以被指定内部操作翻转的抽象标签，不代表两种化学元素。在其他模型中不能交换不同物种来凑出对称性。磁晶体的时间反演涉及磁矩；空间旋转也作用于磁矩方向，不能只用黑白球推断实际磁群。课件中畸变反演与时间反演也应分别定义。</p></details>','24–26');
  let colorMode='plain';const colorPoints=[{position:[-1,0,0],color:'#243e50',radius:.17,label:'黑'},{position:[1,0,0],color:'#cbd8de',radius:.17,label:'白'}];
  new Scene('course-color-before',()=>({radius:1.5,points:colorPoints,lines:axes(1.4)}));new Scene('course-color-after',()=>({radius:1.5,lines:axes(1.4),points:colorPoints.map((p,i)=>({...p,position:colorMode==='swap'?p.position:M.applyMatrix(M.rotationMatrix([0,0,1],Math.PI),p.position),color:colorMode==='plain'?p.color:colorPoints[1-i].color,label:colorMode==='plain'?p.label:colorPoints[1-i].label}))}));
  function updateColor(){['plain','prime','swap'].forEach(id=>$('course-color-'+id).setAttribute('aria-pressed',id===colorMode));$('course-color-result').textContent=colorMode==='prime'?'✓ 2′：位置与黑白标签都重合。旋转和换色这两个分操作单独都不保持对象，组合却可以保持。':colorMode==='plain'?'↗ 普通 2：位置重合，黑白标签相反，因此不是这个双色对象的对称。':'↗ 只换色：位置不变，标签相反，也不能重合。';render();}['plain','prime','swap'].forEach(id=>$('course-color-'+id).addEventListener('click',()=>{colorMode=id;updateColor();}));updateColor();

  $('space-root').innerHTML=section('加入平移：从点群走向空间群','空间操作写成 p′ = R p + t。看清旋转或镜映后，为什么还要走半个周期。',
    '<div class="course-controls"><label for="course-space-op">选择操作 <select id="course-space-op">'+C.operations.map(op=>'<option value="'+op.id+'">'+esc(op.label)+'</option>').join('')+'</select></label><button type="button" id="course-space-camera" class="quiet-button">↺ 视角</button></div><div class="course-space-grid"><div>'+surface('course-space-canvas','空间操作的重复轨迹','course-space-surface')+'<div class="course-space-buttons"><button type="button" class="primary-button" id="course-space-play">播放一次</button><button type="button" class="secondary-button" id="course-space-step">下一步</button><button type="button" class="secondary-button" id="course-space-repeat">再作用一次</button><button type="button" class="secondary-button" id="course-space-reset">回到起点</button><span id="course-space-phase" class="mini-label"></span></div><input type="range" id="course-space-progress" min="0" max="1000" value="0" aria-label="空间操作播放进度"><p>空心点：各次完整操作的位置；实心点：此刻的示踪点。连线表示操作顺序，不是化学键。每次演示先完成旋转或镜映，再完成平移。</p></div><div class="course-property-results"><div class="course-result"><h3 id="course-space-title"></h3><p id="course-space-description"></p><code id="course-space-translation"></code><p class="course-formula">p′ = R p + t</p><p id="course-space-stage"></p></div><div class="course-result"><h3>去掉平移，留下什么？</h3><code id="course-space-point"></code><p>空间群按完整晶格平移取商，得到晶体点群。这里仅展示单个操作的线性部分；螺旋轴变为同重数旋转，滑移面变为镜面。</p><p id="course-space-power"></p></div></div></div><details><summary>读空间群符号：晶格、操作、方向</summary><div class="course-symbol-wrap"><table class="course-symbol-table"><caption>几个课件中的实例</caption><thead><tr><th>空间群</th><th>中心化</th><th>去平移后的点群</th><th>结构例子</th></tr></thead><tbody><tr><td>Fm3̄m</td><td>F · 面心</td><td>m3̄m</td><td>FCC、NaCl、CaF₂</td></tr><tr><td>F4̄3m</td><td>F · 面心</td><td>4̄3m</td><td>闪锌矿 ZnS</td></tr><tr><td>P6₃/mmc</td><td>P · 原始</td><td>6/mmm</td><td>HCP、NiAs</td></tr><tr><td>P6₃mc</td><td>P · 原始</td><td>6mm</td><td>纤锌矿</td></tr><tr><td>P4₂/mnm</td><td>P · 原始</td><td>4/mmm</td><td>金红石</td></tr><tr><td>I4₁/amd</td><td>I · 体心</td><td>4/mmm</td><td>锐钛矿</td></tr></tbody></table></div><p>中心化字母还包括 A/B/C（分别为一组对面中心化，常称底心）和 R（菱方；六方设置中三个格点）。字母 a/b/c/n/d 描述不同滑移分量；m 表示镜面。完整解释还需要轴、面的方向和位置，不能只把所有字符作为不带几何位置的操作组合。</p><p>常用方向约定：单斜采用唯一轴 b；正交依次看 a、b、c；四方与六方首先看主轴 c，再看底面轴族；立方依次涉及 ⟨100⟩、⟨111⟩、⟨110⟩。具体设置要与坐标和完整符号一起阅读。</p><p><a href="https://www.iucr.org/what-we-do/education/pamphlets/space-group-patterns" target="_blank" rel="noopener noreferrer">IUCr · 空间群操作入门 ↗</a></p></details><p class="course-note">此处是空间操作入门，不是完整空间群生成器。螺旋与滑移的幂可在相差晶格平移的意义下回到等价位置；这与在绝对坐标中真正回到原点不同。镜映的中间形变仅用于讲解。</p>','30（衔接 L05 第 2、19、58 页）');
  const spatial={op:C.getOperation('21'),count:0,t:0,playing:false};$('course-space-op').value='21';let frame=0,lastTime=0;
  function stopSpace(){spatial.playing=false;cancelAnimationFrame(frame);frame=0;lastTime=0;}
  const spatialScene=new Scene('course-space-canvas',()=>{const op=spatial.op,n=Math.max(op.n+1,spatial.count+2),orbit=Array.from({length:n},(_,i)=>C.repeat(op,C.seed,i)),base=C.repeat(op,C.seed,spatial.count),current=C.animate(op,base,spatial.t),all=[...orbit,current],center=[0,1,2].map(i=>(Math.min(...all.map(p=>p[i]))+Math.max(...all.map(p=>p[i])))/2),radius=Math.max(1.5,...all.map(p=>M.distance(p,center)));return{center,radius,points:[...orbit.map((p,i)=>({position:p,color:'#94a9b3',hollow:true,label:String(i)})),{position:current,color:'#087e82',radius:.07,label:'此刻'}],lines:[{points:orbit,color:'#b5905788',dash:[4,4]},...(op.type==='screw'?[{points:[[0,0,Math.min(0,center[2]-radius)],[0,0,center[2]+radius]],color:'#087e8277',dash:[6,4]}]:op.type==='glide'?[{points:[[-1,-1,0],[2,-1,0],[2,2,0],[-1,2,0],[-1,-1,0]],color:'#b5905788'}]:[])]};});
  function updateSpace(){const op=spatial.op,base=C.repeat(op,C.seed,spatial.count),current=C.animate(op,base,spatial.t);$('course-space-title').textContent=op.label;$('course-space-description').textContent=op.description;$('course-space-translation').textContent='t = '+xyz(op.translation);$('course-space-point').textContent=op.label+' → '+op.pointLabel;$('course-space-stage').textContent='起点 '+xyz(base)+' → 此刻 '+xyz(current);$('course-space-power').textContent=op.n+' 次完整作用后：'+xyz(C.repeat(op,C.seed,op.n))+'。'+(op.id==='mirror'?'真正回到原坐标。':'朝向相同，绝对坐标仍相差晶格平移。');$('course-space-phase').textContent='已完成 '+spatial.count+' 次 · '+Math.round(spatial.t*100)+'%';$('course-space-progress').value=Math.round(spatial.t*1000);$('course-space-play').textContent=spatial.playing?'暂停':spatial.t===.5&&op.type!=='translation'?'继续平移':'播放一次';$('course-space-repeat').disabled=spatial.t<1||spatial.count>=11;render();}
  function playSpace(){if(spatial.playing){stopSpace();updateSpace();return;}if(spatial.t>=1)spatial.t=0;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){spatial.t=1;updateSpace();return;}spatial.playing=true;lastTime=0;const tick=time=>{if(!spatial.playing)return;if(!lastTime)lastTime=time;const prev=spatial.t;spatial.t=Math.min(1,spatial.t+Math.min(time-lastTime,60)/3200);lastTime=time;if(spatial.op.type!=='translation'&&prev<.5&&spatial.t>=.5){spatial.t=.5;stopSpace();}if(spatial.t>=1)stopSpace();updateSpace();if(spatial.playing)frame=requestAnimationFrame(tick);};updateSpace();frame=requestAnimationFrame(tick);}
  $('course-space-op').addEventListener('change',()=>{stopSpace();spatial.op=C.getOperation($('course-space-op').value);spatial.count=0;spatial.t=0;updateSpace();});$('course-space-play').addEventListener('click',playSpace);$('course-space-step').addEventListener('click',()=>{stopSpace();spatial.t=spatial.op.type==='translation'?1:spatial.t<.5?.5:1;updateSpace();});$('course-space-repeat').addEventListener('click',()=>{stopSpace();spatial.count++;spatial.t=0;updateSpace();});$('course-space-reset').addEventListener('click',()=>{stopSpace();spatial.count=0;spatial.t=0;updateSpace();});$('course-space-progress').addEventListener('input',()=>{stopSpace();spatial.t=Number($('course-space-progress').value)/1000;updateSpace();});$('course-space-camera').addEventListener('click',()=>{Object.assign(spatialScene.camera,{yaw:-.48,pitch:.43,zoom:1});render();});updateSpace();
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopSpace();updateSpace();}});document.addEventListener('symmetry-page-change',e=>{if(e.detail.page!=='advanced')stopSpace();requestAnimationFrame(render);});
  const observer=new ResizeObserver(()=>requestAnimationFrame(render));sceneList.forEach(scene=>observer.observe(scene.canvas));render();
})();
